travis:
  secure:
    BINSTAR_TOKEN: jWrfgRzb0+oimPYH7vm7eXpFN1zQDzPc2DdB/JiDtrEQ9Gbf2c8Yc9uFJpTxkBfCeYlZfE93fWhQNyHrRq9YJIP/bbAhtZsirHi1iFnN33xIpYwR+NsyELV6evV9dm6jvQsRDw0UEBF9CyoDJxR9rZKXfiZ/+gHy87EikgwerGLFIE9LJ2oKB1HklEaPYIK8bNgbIWXsWNG8sOHvbp+kOeHBVgU1izcTYdA68G1R4+NP0HW7Vqmng67aYxYKXBktu+p4JaXupy/IophWf1iGgTCuDPQuDCh2Gj3bNqhlFMPSucIgX5KyAd1Y9zki4Sed2crE7Fd0KkDLqlANYxsGUcNt1Zwr9lTmYHRpDGtNE3ASfM0cDNQk8aMyIW+X/4XJPMaB1qUSlQaUwumVzXbIarAqKpg+dCdNx5l48wRMjb3arjPVwN9X8y77Ni8/KT/j92AtXiTgQImigQX+jOZIizz2W0Mse3zN2unmxzdBpsb6HVFR/dfF9yUCyogbCE4EABKxRe5ACZ/u3nxKxDgIlW3gPe6J53xQdpmlPmzghfyQTIRdXsnt05aLPZ+ZpEqIGSCf6onELwu9T51rW+e1A0gYe/FyyA4eCwMQNKfzQ2SL55bTqmzVdX+uwKy1tyfA20gEOaVUaLOv6QzXmJMEgauH6Oe71NtbeER4dAL8UDg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
