travis:
  secure:
    BINSTAR_TOKEN: qaKWbXl7NSlyGXhFNTT+xBmkVrTUzg4qoEkYy2gFfYe1JTq9LRHK9aCr5lQ1J4mHYjzpqWSZCy6zpiZn8k4kFSHvipvIQwZKkvd1xRmg9z+UoyQH7/B121BYJtv8jzhfzKgzDzhn93vBwKS55UpVIz19USluQuqTcIGBH72QIUav2KaDWoEvFLvu3v75MqMKVQbimh1lga8hfbQcR1JS6JMJ+LihUOHL4JkAThYwziloDAjEZgm2eIy7a6mOzj7E4/+nL7rJgpyotJATwfUwVLdVWE7wnGdgPy5rVOgwHMcYo7/SrAO82qymw5/QgMJ/9GnkE76zcyDUuCNmDm3A4iPe+p3Mya/AB2ZT2fRZCgJRoBSLXIRm1KAJIFYE7ahWXLNZ5RLUuNY5ZSiXjZHroBPfcT4JW/ca98INLshzg31wWErtStsG/FI6I29PJJdmZY4vKs6YsCIdhKtUeSegp9nRJaFtZR2pxODwKq+I/MYTjyQJlOOah/F/vIt6fPHHROnRHKbo+TjKG/jfjG+nHFX1fv45tlT775TwB6nebpVSkgwHsFizwC89kz1m/fH+eGCKnqa+qV4NdIQLCEjSwlP/acjhO06IGdeRFQ3iSzEiVn3H6vnEk9naKtloF4WxGpl6Ql1JwLl3C7uwcbC1nj4Dftf7XqJqjyvpasQsO7k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
