travis:
  secure:
    BINSTAR_TOKEN: RYmWR6L83RwwkgFDjsQds+wDof6+EL8BIch8J6EiWuOulJCB7U/aQO87BexriFOfAZ1ao+oCZRVjrrhELqSTPyLIwru8ak/U2Gn+wuOB9MkKrO7OGp5ZOq7tz0fdvz/JDm+tLfvRV8lmW5ZRhg4P+t9QHQhSHWcXiMllTjrEaMbgS2fzq14Q65pV/mKgxcmdsRq5stQ0J4RmnQRHLGkEzKveKqGI1z4yrOMZoQ61LZewT+z9hXlYJvR3cUOXQeivpjT+ZfFJioTOUvMFC5CFBEIF/IUpa3bsYMg3O3iRFWMTbXINccLFTCewEDK6wrC0YdFrOkmVTY/bvIM1OGUyr51mIcZitGwmo3n544+Hlv1MpehpHfYNn4B5TI1QS+HISwSlQQOcwCmnEouTvgOk8iUVN15H+XF5GpCiMFXq4fTmvpSAOae3C9pNIhEuy10F4YKREJkkzcNASlcFD/ZD8WDoltmBFbyBgphDhdIrfGyQWHou9S8VHOsF6utv2GcL7U/jDR9bfghaamlBJoHMWZGEdslc6I2NriUXJqEVgon0FallyDNdqNSpSyfdlEggrK0T4/i0YiU+JBljTJCC/QCtwHkG5LgZbgwOlhrn8pxOL+8+MUSViJlOqkx6RUtFEVUFYXpg70l3ous8ROQlJQ2QohN0pDbpwa2ETDzDO6w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
